### ISSUE TITLE
Provide user feedback in empty panes

### ISSUE THREAD

**Issue by isabela-pf** [spyder-ide/ux-improvements#11]
Several panes in Spyder might have no content until the user does a specific action. Right now, most of these panes look like empty rectangles without any explanation for why they are empty, so users could easily think there is an error, that they have done something that interrupted the pane’s function, or that it is loading very slowly. 

It’d be a better experience if Spyder is transparent about two things: 
1. What is happening to make the pane empty (for example, no plots generated yet in the Plots pane) 
2. What can users do to make the pane function (like run the Editor with plot-generating code)

There’s a few different ways we can solve this lack of feedback, but it should have a visual relationship or similar approach and feel to the work on a combined Help pane’s “home” as shown in #9 since they are both in-pane messages (though that is more of an index of help options than an empty pane). 

A few notes about these mockups:
- While there are multiple panes that need this treatment, I am showing mockups with the Plots pane only since I’m exploring general directions for now.
- I'm not spending time putting in the pane's toolbars for now, though they should still be there.
- I want to iterate on the messages and make sure they are accurate. These are rough ideas.

## Option 1
This one matches the Help pane work almost exactly. I don’t think it is the strongest approach visually, but if we want the panes to match exactly this might be the direction to explore.

<img width="559" alt="3" src="https://user-images.githubusercontent.com/50221806/90457655-fd7e4c00-e0b0-11ea-9286-da45819c2430.png">

## Option 2
This is the next closest to the Help pane work, but a little more balanced for the space.

<img width="559" alt="4" src="https://user-images.githubusercontent.com/50221806/90457663-02db9680-e0b1-11ea-9ed8-4dde0f45cfd0.png">

## Option 3
Here I started to explore if there was something useful an empty pane could do on top of communicating basic states of the pane to users. In this iteration, the empty pane messages are accompanied by a list of imported visualization packages so users can know what they could be generating plots from before they have even done it. I’m not sure if tracking visualization package imports is a useful or technically feasible idea (Does the Plots pane even know what is happening in the Editor before it is run?). It’s here for review anyways, and I’d appreciate the feedback. Maybe a different set of useful plot-related information fits here instead?

<img width="559" alt="13" src="https://user-images.githubusercontent.com/50221806/90457670-0838e100-e0b1-11ea-8d22-ab7e732ffd10.png">

## Option 4
This option has the least in common with the Help pane reworking, but breaks up the already text-heavy Spyder UI with a simple illustration of what the pane can look like when it has content. It is also the furthest from anything that currently exists in Spyder UI, though there aren’t any comparable messages that I’m aware of.

<img width="559" alt="12" src="https://user-images.githubusercontent.com/50221806/90457679-11c24900-e0b1-11ea-974c-d9d673a34061.png">

**Comment by juanis2112** [comment]
We like option 4 but we will include the supported packages for the plots pane.

**Comment by isabela-pf** [comment]
I made a list of what panes I think could benefit from this kind of “empty” pane treatment. Some aren’t as empty as the blank space of the plots pane but still don’t provide any kind of feedback until run, so I think they could benefit from similar treatment.
- Plots
- Variable Explorer
- Code Analysis
- Profiler
- Projects (not pictured below)

In the case of Code Analysis and Profiler panes, I’m undecided whether or not they should keep their current content and just add a message. For now, I’ve posted it with an illustration since that takes more work to visualize than deciding we want to leave it mostly as is.

On that note, here are some more explorations of what the illustrations could look like and what messages might makes sense. Feedback on both is appreciated.

First is an illustration style following the lead of the last post. These look like approximations of what a given pane will look like once there is content in it.

### Plots
Almost the same as the last round. Has an updated message, but I left a blank for proper wording around which packages were supported.
<img width="559" alt="plot14" src="https://user-images.githubusercontent.com/50221806/93271638-9fed2600-f768-11ea-94f7-a920c2ed371e.png">

### Variable Explorer
<img width="559" alt="variable25" src="https://user-images.githubusercontent.com/50221806/93271719-cca13d80-f768-11ea-83e8-5f9e8c06b8e2.png">

### Code Analysis
<img width="559" alt="analysis30" src="https://user-images.githubusercontent.com/50221806/93271735-d5920f00-f768-11ea-84a0-83f56edbe320.png">

### Profiler
<img width="559" alt="profile28" src="https://user-images.githubusercontent.com/50221806/93271750-e04ca400-f768-11ea-83a7-a507a4df8b69.png">

Second, I experimented with a less literal approach that is more playful and possibly more informative. While seeing what a full pane might looks like can be helpful in cases like the Plots pane where a plot is easy to identify, the difference between some panes is harder to tell (both the Variable Explorer and Profiler panes look like tables). 

### Plots
<img width="559" alt="plot32" src="https://user-images.githubusercontent.com/50221806/93271823-05d9ad80-f769-11ea-82b8-d82f32ad0005.png">

### Variable Explorer
I think this one needs the most work if we are interested in this style. It's still quite rough.
<img width="559" alt="variable34" src="https://user-images.githubusercontent.com/50221806/93271830-0a05cb00-f769-11ea-92ab-f885ce4dc784.png">

### Code Analysis
<img width="559" alt="analysis36" src="https://user-images.githubusercontent.com/50221806/93271846-1722ba00-f769-11ea-8acf-9f5fd892cf64.png">

### Profiler
<img width="559" alt="profile37" src="https://user-images.githubusercontent.com/50221806/93271855-1c800480-f769-11ea-85ec-94630867d958.png">

I'll re-post these illustrations on their own in #14 for consistency and review.

**Comment by juanis2112** [comment]
List of Panes:

- [ ]  Plots
- [ ]  Variable Explorer (Modify it)
- [ ]  Profiler (Modify)
- [ ]  Code analysis
- [ ]  Projects
- [ ]  Find

**Comment by isabela-pf** [comment]
It's time to get some ideas for the panes we haven't decided on yet. Hooray! Much of the text still needs feedback either to clarify it is accurate or if there is a better description. 

### Variable Explorer 
It’s returned and it’s polished. The major change here is a much cleaner telescope.
<img width="559" alt="54" src="https://user-images.githubusercontent.com/50221806/114456321-92c6d700-9b91-11eb-89d4-663839cf0ac0.png">

### Projects
The first option is more literal with an emphasis on projects being made of directories. This is not my favorite choice since I don’t know that it adds more clarity. Having perspective (like the open folder) does not fit will with the illustration style either (and the closed folder option covers the file design almost completely).
<img width="559" alt="57" src="https://user-images.githubusercontent.com/50221806/114456588-e20d0780-9b91-11eb-93c4-864ab36d8b03.png">

The second option is more fun and based on the idea of a project on a desk. The main concern here is if that this doesn’t make it clear what projects are any more than the name “projects” does.
<img width="559" alt="74" src="https://user-images.githubusercontent.com/50221806/114456624-ec2f0600-9b91-11eb-8caf-a1d0fc5065c4.png">

### Find
First is the version that matches Code Analysis and Profiler file illustrations. To add a degree of separation from those two, the magnifying glass is in a different location.
<img width="559" alt="66" src="https://user-images.githubusercontent.com/50221806/114456639-f0f3ba00-9b91-11eb-938b-39c6a34733ab.png">

If we want to emphasize more complete separation from Code Analysis and Profiler, we don’t have to use the file illustration at all. This version is just searching a group of vague rectangles.
<img width="559" alt="65" src="https://user-images.githubusercontent.com/50221806/114456664-f6510480-9b91-11eb-8283-b8f265b956a9.png">

### History
This is one of the panes I am still least satisfied with. Once again working off the file idea (since it looks like a list and the History pane pulls from an automatically generated file), this combines the Profiler’s clock illustration with the standard “reset”/”go back” icon. Just like the first Find option, the clock is in a different location to keep it from being more easily mistaken for the profiler. 
<img width="559" alt="71" src="https://user-images.githubusercontent.com/50221806/114456675-fb15b880-9b91-11eb-9664-4d4bc3620df6.png">

I also have an alternate option for the upper text (the one that says why the pane is empty). It might be more helpful to say "You haven’t run commands in your console yet."

**Comment by juanis2112** [comment]
Variable explorer:
We like the telescope but maybe try to space out more elements
Projects:
We like Option 1 but we need to think about the default size of the pane. 
Find: 
Stephannie likes option 2 because the concept of "find" is more general and I like option 1 because it matches the "file image" in some of the other images. @ccordoba12 it's your choice.
History:
Maybe try adding something inside the file to reference that this is the history of the terminal. ('#', or 'cmd' or 'py', '[1]')

**Comment by isabela-pf** [comment]
Here's the next round of illustrations based on the above feedback (except for Find since that's still waiting for a little more feedback).

### Variable Explorer
I redistributed the letters and sparkles a little bit to make it more balanced. I don't think it adds much, but that's up to you!

<img width="559" alt="92" src="https://user-images.githubusercontent.com/50221806/115071132-b1d3aa80-9eaa-11eb-8f35-8a80cb1c6e7d.png">

### Projects
Even though Projects will default to a different pane size, I don't think it's wise to make illustrations in a different size/ratio since (1) it can be resized and (2) I don't think it will make a big difference. This mockup does show how this looks more spaced out and scaled down, though. 

I could also use feedback on what info makes sense in the lower feedback text. Let me know what you think!

<img width="339" alt="81" src="https://user-images.githubusercontent.com/50221806/115071145-b8622200-9eaa-11eb-8bbf-ee94fcd0513c.png">

### History
I think the [1] approach looked the best by far and was the most recognizable from the console. Of course, I can show mockups of the other directions if you want.

<img width="559" alt="90" src="https://user-images.githubusercontent.com/50221806/115071553-3d4d3b80-9eab-11eb-9ea8-7446bad25357.png">

### Plots
Corrects the size of the sparkles. 

<img width="559" alt="48" src="https://user-images.githubusercontent.com/50221806/115071650-5eae2780-9eab-11eb-8840-d516056b1e81.png">

### Profiler
Adds sparkles to match the rest of the illustrations.

<img width="559" alt="89" src="https://user-images.githubusercontent.com/50221806/115071680-68378f80-9eab-11eb-8af7-800c265ff8be.png">

### Code Analysis
Also adds ✨ sparkles ✨.

<img width="559" alt="87" src="https://user-images.githubusercontent.com/50221806/115071807-8e5d2f80-9eab-11eb-8c8b-b3d01bb1b9c4.png">

**Comment by juanis2112** [comment]
Find pane:
Option 1: Maybe try to use a stack of files and something that says that they are text files since it doesn't work for other stuff.
Variable explorer:
READY :)
Projects: 
READY :)
History:
-Use multiple numbers in several lines and add colons ':' after them
-Try the one that has only one number but with a colon at the end
Plots:
READY :)
Profiler:
READY :)
Code analysis:
READY :)

**Comment by isabela-pf** [comment]
Next round!

## Find pane
To show the contents of the second file, it needs to be more spaced out.
<img width="559" alt="95" src="https://user-images.githubusercontent.com/50221806/116504048-57ecc080-a86c-11eb-8a17-3021a2b9c968.png">

We could also go the opposite direction and show more files tighter together.
<img width="559" alt="105" src="https://user-images.githubusercontent.com/50221806/116504143-8a96b900-a86c-11eb-9afe-b177fd8cd446.png">

## History
As requested, here are the two options!
<img width="559" alt="100" src="https://user-images.githubusercontent.com/50221806/116504219-aa2de180-a86c-11eb-949f-3439e2a160f9.png">
<img width="559" alt="104" src="https://user-images.githubusercontent.com/50221806/116504222-ad28d200-a86c-11eb-8d7e-0d20fa0ae80f.png">

## Breakpoints
This is a very rough idea, but I didn't want it to hold up the other work. The bug needs a lot more refinement, but if it doesn't look "icky" I'm happy to keep working on this direction.
<img width="559" alt="108" src="https://user-images.githubusercontent.com/50221806/116504385-00028980-a86d-11eb-9b5a-d543de45571d.png">

___

For the approved icons, here they are cleaned up and as pngs.
<img width="300" alt="48" src="https://user-images.githubusercontent.com/50221806/116504653-ab134300-a86d-11eb-8424-4540365486e5.png">
<img width="300" alt="81" src="https://user-images.githubusercontent.com/50221806/116504658-ad759d00-a86d-11eb-9160-2d1b4735da67.png">
<img width="300" alt="87" src="https://user-images.githubusercontent.com/50221806/116504660-af3f6080-a86d-11eb-9aef-fafe1e4078d7.png">
<img width="300" alt="89" src="https://user-images.githubusercontent.com/50221806/116504662-b0708d80-a86d-11eb-9d56-1cd417558a9e.png">
<img width="300" alt="92" src="https://user-images.githubusercontent.com/50221806/116504666-b1a1ba80-a86d-11eb-8e31-425beb38eb1e.png">

**Comment by isabela-pf** [comment]
More updates! We are almost there!

### History
I fixed the incorrect colon placement (sorry, my mistake!) If there's nothing else about this option, I'm happy to export is as an isolated png.
<img width="559" alt="110" src="https://user-images.githubusercontent.com/50221806/117763638-fcadbd00-b1df-11eb-8c7e-ee90daf46bb4.png">


### Breakpoints
Updated bug options for you. I'm still not certain about these options, but I've been working through a lot of bug ideas and I just wanted to post some options for you all to see.
<img width="559" alt="115" src="https://user-images.githubusercontent.com/50221806/117763657-09321580-b1e0-11eb-995d-3fb6f1fafaf0.png">
<img width="559" alt="127" src="https://user-images.githubusercontent.com/50221806/117763659-09caac00-b1e0-11eb-9d47-eee12c911a35.png">



### Find Pane
It's approved! Here it is as a cleaned up png.
![105](https://user-images.githubusercontent.com/50221806/117763400-99bc2600-b1df-11eb-9d73-19311daeca85.png)

**Comment by juanis2112** [comment]
Breakpoints:

Maybe try the bug with a head but we like the eyes and the legs.

**Comment by isabela-pf** [comment]
### Breakpoints

One more for breakpoints with a different bug! 🐛 
<img width="559" alt="131" src="https://user-images.githubusercontent.com/50221806/118026046-41874000-b315-11eb-86ce-4859d8fbb8b3.png">
