### ISSUE TITLE
Variable Explorer issues

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/ux-improvements#17]
- [ ] Fix default width of columns to avoid disappearing names of them
- [ ] Add tooltip when complete names are not visible in collapsed columns (name, type, size, variable names)
- [ ] Move resizing columns and rows from context menu to options menu 
- [ ] Remove show max/min from context menu
- [ ] Add Filter button to activate/deactivate the filters for the variables. (~Unchecked~ Checked by default. See https://github.com/spyder-ide/spyder/pull/20868#discussion_r1215065240)
- [ ] Add "edit filters" option in the context menu to edit the filters, which goes to preferences.
~- [ ] In the edit filters option in preferences the options currently activated by defaullt should still be checked by default.~ See https://github.com/spyder-ide/spyder/pull/20868#discussion_r1216973873

**Comment by ccordoba12** [comment]
I have a couple of additional suggestions to make it discoverable that the Variable Explorer entries are clickable and can open additional viewers for different variable types:

1. Change the mouse shape to `Qt.PointingHandCursor` when hovering the Variable Explorer.
2. Make that a single mouse click open our viewers for Dataframes, Numpy arrays, etc.
