### ISSUE TITLE
Opinion about the new loading screen

### ISSUE THREAD

**Issue by impact27** [spyder-ide/ux-improvements#57]
Having seen the new loading screen for spyder, I must say I miss the spyder web picture.
The new picture feels like it is a random corporate stock photo (even if spyder is open on the laptop :) ) And also it is quite high for a loading screen (almost the size of a full window). I am probably biased as I like to see pictures of nature.

**Comment by ccordoba12** [comment]
Hey @impact27, about your comments:

> And also it is quite high for a loading screen (almost the size of a full window)

That was fixed already. We resized the image to ne 500px in width.

> I am probably biased as I like to see pictures of nature.

Sorry that you didn't like the new splash screen but the previous one didn't match any color in the interface. That's why we decided to change it.

**Comment by ccordoba12** [comment]
I don't know if @isabela-pf has something else to add.
