### ISSUE TITLE
Spyder splash screen low resolution + other things

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/ux-improvements#61]
Here's the splash screen that I see with my Spyder v5.1.1:
<img src="https://user-images.githubusercontent.com/14086031/128605373-647d3e65-7c6a-4045-ab8d-f4a47e46c516.png" width=50%>
I think it could be improved on three fronts:

1. The top-left/right corners are not round (like the bottom corners)
2. The splash screen is low-resolution and doesn't appear sharp on high-res monitors
3. (this might be opinionated, but anyway) the background photo, in my opinion, doesn't really add any more value to the splash screen (a person sitting next to a laptop seems a bit random to me for a splash screen of an IDE software). In fact, I think it's detracting from the beauty of the splash screen, compared to just a simple gradient red (instead of a splash screen). Again, this is my opinion, so don't take it personally.

**Comment by ccordoba12** [comment]
> The top-left/right corners are not round (like the bottom corners)

That's by design.

> The splash screen is low-resolution and doesn't appear sharp on high-res monitors

That's worrisome. Could you post a screenshot of how it looks in a high-res monitor?

> the background photo, in my opinion, doesn't really add any more value to the splash screen

That's certainly your opinion and we disagree with it. Please see the end of our video for the rationale:

https://youtu.be/3j6GJPUqYwQ?t=2729

**Comment by ma-sadeghi** [comment]
Thanks for your quick reply. Here's a screenshot from a 4K monitor:
![image](https://user-images.githubusercontent.com/14086031/128607747-cecaa8cf-25f0-4980-a75e-4c5eafddb92d.png)

**Comment by ccordoba12** [comment]
Thanks @ma-sadeghi! I agree that the image and especially the text have a lot of pixelation.

@isabela-pf, is there something we can do about it?

**Comment by ma-sadeghi** [comment]
Also, here's an screenshot of my taskbar: 

![image](https://user-images.githubusercontent.com/14086031/128645610-50402179-7531-47bb-a641-28430a6be552.png)

in which the Spyder icon is low-resolution (compare it with the one next to it on the left, which is for Mathematica, or VS Code, etc.)

**Comment by andfoy** [comment]
I couldn't reproduce this issue in my HiDPI screen, the icon looks pretty defined
![Screenshot 2021-08-17 230716](https://user-images.githubusercontent.com/1878982/129812367-7c79c3b8-2af5-4123-90f4-f0bb0f6e455f.png)

**Comment by ma-sadeghi** [comment]
@andfoy could you right click on the icon and let me know where you .ico is located? Mine is in 
```bash
%USERPROFILE%\mambaforge\Scripts\spyder.ico
```
which I converted to PNG so GitHub allows me to upload it:
![spyder](https://user-images.githubusercontent.com/14086031/129828793-b6f4fbdd-e76a-4166-8d46-5ee541a708e5.png)

**Comment by ccordoba12** [comment]
Ok, I think I know what the problem is: the size of our ico file is too small (32x32 px) for high dpi screens. In contrast, the VSCode ico file is 128x128 px (just checked it).

So I think it's just a matter of increasing the size and we'll be good. @isabela-pf, could you take care of that? Thanks!

**Comment by ccordoba12** [comment]
This file whose size we need to increase:

https://github.com/spyder-ide/spyder/blob/5.x/img_src/spyder.ico

**Comment by ma-sadeghi** [comment]
@ccordoba12 Great, thanks! Could you maybe do the same for the splash screen?

**Comment by ccordoba12** [comment]
Although the problem for that is different, @isabela-pf is already working on a fix. Both things will be available in Spyder 5.2.0, to be be released at the end of September,

**Comment by ma-sadeghi** [comment]
I updated my Spyder to 5.1.2, but the splash screen is still low-res (although better than what it used to be).
![image](https://user-images.githubusercontent.com/14086031/131918921-5cb8ce82-0962-4889-9635-a9da97535b2e.png)
For comparison, here's the splash screen of Mathematica on the same monitor:
![Untitled](https://user-images.githubusercontent.com/14086031/131919258-a1350278-3a3c-4713-8599-59eb2dd08e8a.png)

**Comment by ccordoba12** [comment]
I think that's the best we can do because we're using and not just a figure.

I'm a bit surprised that the logo and "Version 5" still look pixelated. @isabela-pf, what do you think?

**Comment by isabela-pf** [comment]
I'm sorry to hear it. I know it's not what anyone wants to hear, but I'm not sure what to do next. The last PR remade the splash screen with me double checking it wasn't actually converting some part of the SVG to a bitmap early by accident, and @steff456 and @andfoy corrected the way the splash screen is called for the same reason.

Can I ask if it's just the splash screen now, or also the icons? It looks like they are still a little blurry in the screen shot you posted.

**Comment by ma-sadeghi** [comment]
@isabela-pf Thanks for your reply. The low-res taskbar icon you see in my screenshot is because it hasn't been updated. I removed it and re-added it and it got fixed. The only issue is the splash screen.

**Comment by steff456** [comment]
@ma-sadeghi, I'm afraid there's nothing else we can do to enhance the resolution of the splashscreen. As @isabela-pf already mentioned Qt expects a bitmap to be loaded as a splashscreen, we cannot load a high res svg because it will be converted to a bitmap inevitably loosing resolution. Maybe in future versions of Qt they will change this restriction, and we will be able to load an image rather than a bitmap.

**Comment by ccordoba12** [comment]
This could help: https://stackoverflow.com/questions/56547487/display-image-without-loosing-quality
