### ISSUE TITLE
When I use the Spyder, it will be accompanied by a form

### ISSUE THREAD

**Issue by A-Pai** [spyder-ide/ux-improvements#63]
When I  start Spyder from .py file, it will be accompanied by a form，just as below，can it be hidden？

![image](https://user-images.githubusercontent.com/5112397/131201297-a1b9f6e7-18e8-4281-896d-cb0a39e503ae.png)

my spyder is：
![image](https://user-images.githubusercontent.com/5112397/131201399-f10ef491-476d-461a-8312-4263076854b5.png)

**Comment by ccordoba12** [comment]
Hey @A-Pai, thanks for reporting. Unfortunately, that's something we can't fix in Spyder.

Please report it to Anaconda instead:

https://github.com/ContinuumIO/anaconda-issues/
