### ISSUE TITLE
Add menu for list/tables (from double click) to a static toolbar

### ISSUE THREAD

**Issue by dpturibio** [spyder-ide/ux-improvements#67]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Enhancement: I would like to propose a enhancement for the menu popped when a list/table is right-clicked. As my team is frequently working on lists and tables in our internal Spyder Plugin, we noticed that right-clicking every time in a row to show table/list's options is not the best way to do this. 
With this in mind, I would like to suggest incorporating a static toolbar in the top of the list/table window as shown in the picture bellow. 

![Screenshot_spyder](https://user-images.githubusercontent.com/19315417/144337890-54a72f05-71d8-4274-a98b-4ebb468f2cdb.png)

### What steps reproduce the problem?

1. Create any list in the editor, for example: test_list = [1,2,3,4,5]
2. Click in Run->Run with "IPython console" and "Variable explorer" active
3. Double-click in test_list variable in "Variable explorer" window.
4. In the opened window, right click on any item and menu will show up

### What is the expected output? What do you see instead?
Expected output is to have a static edition toolbar in the window further on the right-clicked menu
If this enhancement is approved, I can work on it as previously worked on spyder-ide/spyder#13371

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.0.5
* Python version: 3.8.10
* Qt version: 1.9.0
* PyQt version: 5.12.3
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dpturibio** [comment]
@CAM-Gerlach and @dalthviz, thank you for your feedback.
@dalthviz: I agree in disabling if nothing/multiple items are selected, depending of the action(in remove action, it is not necessary for multiple items for example, only for none). I can work on this checks for the toolbar.
@CAM-Gerlach: regarding your questions on how long the list is and how big the window is, it won't be a problem as the window has a scroll bar and can be resized by the user accordingly to his needs.
I checked with my team about the shortcuts, and they all prefer a static toolbar in the top of the window.  It's visually more pleasing and functional, but we do not disagree in having also a shortcut.
Please let me know what you think.

**Comment by dalthviz** [comment]
I would say that makes sense to me (to have shortcuts for the actions in the toolbar :+1: ). Also just in case, do you have any suggestions/ideas regarding this @isabela-pf ?

**Comment by dpturibio** [comment]
Hello guys, sorry for the long time without contacting.
I was working on this improvement and I would like to share some code with you for suggestions and maybe having a direction to resolve some issues:
@dalthviz, could you help me to mark the best person to give comments if is not you?

For the toolbar addition, I had to change two classes in spyder/widgets/collectionseditor.py
in class BaseTableView(QTableView, SpyderConfigurationAccessor), method setup_menu, changed:
```python
return menu
```
to
```python
return [menu, menu_actions]
```

in order to have get the menu actions. And I suggest to change the method's name from setup_menu to setup_menu_and_toolbar


 in class CollectionsEditorTableView(BaseTableView), __init__ method, change:
```python
self.menu = self.setup_menu()
```
to
```python
self.menu, toolbar_items = self.setup_menu_and_toolbar()
```

and add the code:
```python
self.toolbar = SpyderToolbar(parent = parent, title = 'Editor toolbar')
self.toolbar.setMinimumWidth(700)#necessary as it is not mainwindow, toolbar width is not resized
for item in toolbar_items:
   if item != None:
      self.toolbar.addAction(item)
```

the final result is:
![toolbarspyder](https://user-images.githubusercontent.com/19315417/155254093-7f3084dd-df9c-4d66-9132-722f4b3c8472.png)

Question 1: how to auto-resize toolbar when not dealing with main window(for not need to use setMinimumWidth)? Any ideas?
Question 2: how to accomodate toolbar in the window without overlapping the list?(as in the image)

**Comment by dalthviz** [comment]
Hi @dpturibio thank you for checking in again! I would say that probably @isabela-pf input about how this should look and work could be nice (also just in case anyone else has comments pinging @spyder-ide/core-developers ). Regarding your questions, I think the you will need to add the toolbar to the widget layout which is not in the `CollectionsEditorTableView` widget but in his parent (the `CollectionsEditorWidget` class at `spyder/widgets/collectionseditor.py`).

Also, regarding the change in the `setup_menu` method, I think you maybe will need to also do some changes in the `RemoteCollectionsEditorTableView` which also inherits from the `BaseTableView` and calls `setup_menu`.

Let us know if you have more comments or questions and thanks again for working on this!

**Comment by dpturibio** [comment]
Perfect observation @dalthviz. Adding the toolbar in **CollectionsEditorWidget** did the trick!

![spyderToolbar](https://user-images.githubusercontent.com/19315417/155435504-5578fdce-da88-4b26-9787-8b9e653e9d63.png)

I will work on **RemoteCollectionsEditorTableView** class in order to handle the call to **setup_menu** method and share with you soon.
Thanks a lot for the tips.

**Comment by dpturibio** [comment]
regarding **setup_menu** method of **RemoteCollectionsEditorTableView** class, could be modified as follows:
from:
```python
def setup_menu(self):
```
to
```python
def setup_menu(self, setup_toolbar=False):
```
and then check
```python
if setup_toolbar:
   return [menu, menu_actions]
else:
   return menu
```
what do you think @dalthviz ? If you are ok with these changes, let me know if I can work on a merge request for it.
Thank you.

**Comment by CAM-Gerlach** [comment]
As a side note, changing the return type like this is generally a practice that is often best avoided, but that ultimately comes down to the current conventions and patterns in the Spyder API, which @dalthviz and the others would be better informed on than I.

**Comment by dalthviz** [comment]
Hi again @dpturibio ! Thinking about the `setup_menu` maybe we could save the actions in a class attribute instead of changing the method `return` structure. So, something like:

```python
def setup_menu(self):
    ...
    self.menu_actions = menu_actions
    return menu
```
And then we would be able to get the menu actions from the `RemoteCollectionsEditorTableView` or `CollectionsEditorTableView` on the `CollectionsEditorWidget` with something like:

```python

self.editor.menu_actions
```

In any case, if you have already some code you can make a PR :) Then we can check the functionality and suggest or comment on the code directly. Let us know what do you think!

Also thanks @CAM-Gerlach for the feedback :+1:

**Comment by dpturibio** [comment]
Thank you for the contributions @dalthviz @CAM-Gerlach
Just a last question: which branch should I derive the code from?

**Comment by dalthviz** [comment]
No problem @dpturibio and I think that probably you should use the `5.x` branch, but just in case pinging @ccordoba12 to double check

**Comment by dpturibio** [comment]
Thank you @dalthviz for the guidance. I submitted the PR as you can see above.
What is the workflow from now on? Let me know if I need to take some further action.

**Comment by dalthviz** [comment]
Glad to help @dpturibio and now I think we could continue the discussion over the PR (so we can check the actual code and give you feedback over there). Could you request me as a reviewer in the PR you opened to not forget to check it please? Thanks for your interest and work on this one!
